name: CI Pipeline

on:
  push:
    branches: 
      - "**"
  pull_request: 
    branches: [ main ]

jobs:
  get-version:
    name: "Get Version"
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} 
          fetch-depth: 0
      - name: Get next semantic version
        id: version
        uses: codacy/git-version@2.5.3
        with:
          release-branch: ${GITHUB_REF#refs/heads/}
          minor-identifier: "feat:"
      - name: Show version
        run: |
          echo VERSION: ${{ steps.version.outputs.version }} 
          echo PREVIOUS_VERSION: ${{ steps.version.outputs.previous-version }} 
