name: CI Pipeline

on:
  push:
    branches: 
      - "**"
  pull_request: 
    branches: [ main ]

jobs:
  get-version:
    name: "Get Version"
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} 
          fetch-depth: 0
      - name: Get next semantic version
        id: version
        uses: codacy/git-version@2.4.0
        with:
          release-branch: "feat/jira02"        
          minor-identifier: "feature:/feat:"
      - name: Show version
        run: |
          echo VERSION: ${{ steps.version.outputs.version }} 
          echo PREVIOUS_VERSION: ${{ steps.version.outputs.previous_version }} 
